app:
    resource: '@AppBundle/Controller/'
    type: annotation

movies:
    type: rest
    resource: AppBundle\Controller\MoviesController
    
movies_post:
    path: /movies
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\MoviesController:postMoviesAction
        _format: json

#movies_patch:
#    path: /movies
#    methods: [PATCH]
#    defaults:
#        _controller: AppBundle\Controller\MoviesController:patchMovieAction
#        _format: json

persons:
    type: rest
    resource: AppBundle\Controller\PeopleController
    
persons_post:
    path: /people
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\PeopleController:postPeopleAction
        _format: json

movies_roles_post:
    path: /movies/{movie}/roles
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\MoviesController:postMovieRolesAction
        _format: json

users:
    type: rest
    resource: AppBundle\Controller\UsersController
    
messages_get:
    path: /messages
    methods: [GET]
    defaults:
        _controller: AppBundle\Controller\MessagesController:getMessageAction
        _format: json
    
users_post:
    path: /users
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\UsersController:postUserAction
        _format: json

#users_patch:
#    path: /users/{theUser}
#    methods: [PATCH]
#    defaults:
#        _controller: AppBundle\Controller\UsersController:patchUserAction
#       _format: json

tokens:
    type: rest
    resource: AppBundle\Controller\TokensController
    
