# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
            entity:
                class: AppBundle:User
                # AppBundle:User is an alias for AppBundle\Entity\User (to find Symfony doc that explains how this is determined)
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_api:
            # Symfony executes the anonymous authentication provider to handle
            # the situation where createToken() returns null. AnonymousToken is returned.
            # See https://symfony.com/doc/3.4/security/api_key_authentication.html
            anonymous: true
             # no user session created. Authentication Token is sent with each request
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator
    
    #access_decision_manager:
    #    strategy: unanimous
    #    allow_if_all_abstain: false
